CREATE TABLE usuarios (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    perfil VARCHAR(20) NOT NULL DEFAULT 'ADMIN'
);

CREATE TABLE leads (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    modelo_interesse VARCHAR(100) NOT NULL,
    unidade VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NOVO',
    criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);